name: 'JSON Syntax Validator'
author: 'Sinan Shaban'
description: 'This action validates the syntax of a JSON file'
inputs:
  paths:
    description: Comma separated list of files or directories
    required: true
    type: string[]
runs:
  using: 'composite'
  steps:
    - run: |
        set +e
        invalidFiles=0
        for file in "${{ inputs.paths }}"
        do
            echo "Validating file:" $file
            jq empty $file

            if [ "$?" -ne 0 ]
            then
              invalidFiles=$((invalidFiles+1))
              echo ">>>Failed"
            else
              echo ">>>Valid"
            fi

            echo -e "\n"
        done

        if [ $invalidFiles -gt 0 ]
        then
          echo "Invalid files:" $invalidFiles
          exit 1
        fi
      shell: bash