name: 'JSON Syntax Validator'
author: 'Sinan Shaban'
description: 'This action validates the syntax of a JSON file'
inputs:
  paths:
    description: Comma separated list of files or directories
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        echo paths value: ${{ inputs.paths }}
        list=($(echo ${{ inputs.paths }} | tr "," "\n"))
        invalidFiles=0
        for path in ${list[@]}
        do
            echo "Validating file: "$path
            cat $path | jq . 2>&1 || true
            if [ "$?" -ne 0 ]
            then
                invalidFiles=$((invalidFiles+1))
                echo "NOT VALID"
            else 
                echo "VALID"
            fi
        done

        if [ $invalidFiles -gt 0 ]
        then
          echo "INVALID FILES: "$invalidFiles
          exit 1
        fi
      shell: bash