name: 'JSON Syntax Validator'
author: 'Sinan Shaban'
description: 'This action validates the syntax of a JSON file'
inputs:
  paths:
    description: Comma separated list of files or directories
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        echo paths value: ${{ inputs.paths }}
        list=($(echo ${{ inputs.paths }} | tr "," "\n"))
        invalidFiles=0
        for path in ${list[@]}
        do
            echo "Validating file: "$path
            cat $path
            error=$(cat $path | jq .)
            if [ "$?" -ne 0 ]
            then
                echo "NOT VALID"
            else 
                echo "VALID"
            fi
        done

        echo "INVALID FILES: "$invalidFiles

        exit 1
      shell: bash